metafora_archeologia="Ponieważ wybrałeś: - język polski, - zainteresowanie historią,- zainteresowanie zwiedzaniem zabytków."
metafora_architektura="Ponieważ wybrałeś: - matematyka, - zainteresowanie naukami przyrodniczymi. rysunkiem technicznym, - kreatywność, - brak zainteresowania pracą w laboratorium."
metafora_biologia="Ponieważ wybrałeś: - matematyka, - zainteresowanie naukami przyrodniczymi, pracą w laboratorium i fauną oraz florą."
metafora_budownictwo="Ponieważ wybrałeś: - matematyka, - zainteresowanie naukami przyrodniczymi, rysunkiem technicznym, - brak zainteresowania pracą w laboratorium, - brak kreatywności."
metafora_chemia="Ponieważ wybrałeś: - matematyka, - zainteresowanie naukami przyrodniczymi i pracą w laboratorium, sybstancjami chemicznymi, - brak zainteresowań biologią."
metafora_dziennikarstwo="Ponieważ wybrałeś: - język polski, - brak zainteresowania historią i nauką języków, - umiejętność przeprowadzania wywiadów lub pisania artykułów."
metafora_ekonomia="Ponieważ wybrałeś: - matematykę,  - brak zainteresowań naukami przyrodniczymi i pracą księgowego, - zainteresowanie nowinkami finansowymi."
metafora_fizyka="Ponieważ wybrałeś: - matematyka, - zaniteresowanie naukami przyrodniczymi, pracą w laboratorium, - brak zainteresowania biologią oraz chemią."
metafora_weterynaria="Ponieważ wybrałeś: - matematyka, - zainteresowanie naukami przyrodniczymi i leczeniem zwierząt, - brak zainteresowania pracą w laboratorium, rysunkiem technicznym."
metafora_geografia="Ponieważ wybrałeś: - matematyka, - zainteresowanie naukami przyrodniczymi, wiedzą geograficzną, - brak zainteresowania pracą w laboratorium, rysunkiem technicznym i leczeniem."
metafora_historia="Ponieważ wybałeś: - język polski, - zainteresowanie historią, - brak zainteresowania zawodem prawnym i zwiedzaniem zabytków."
metafora_informatyka="Ponieważ wybrałeś: - matematyka, - zainteresowanie nowoczesną technologią, - brak zainteresowania naukami przyrodniczymi."
metafora_logistyka="Ponieważ wybrałeś: - matematyka, - brak zainteresowań naukami przyrodniczymi, nowinkami finansowymi, technologią, - zainteresowanie transportem i produkcją."
metafora_matematyka="Ponieważ wybrałeś: - matematyka, - brak zainteresowań naukami przyrodniczymi, nowinkami finansowymi, techonolgią i oraz transportem i produkcją."
metafora_medycyna="Ponieważ wybrałeś: - matematyka, - zainteresowanie naukami przyrodniczymi i leczeniem ludzi, - brak zainteresowania pracą w laboratorium, rysunkiem technicznym."
metafora_pedagogika="Ponieważ wybrałeś: - język polski, - brak zainteresowania  historią, nauką języków, pisaniem artykułów, - interesuje Cię wychowanie."
metafora_prawo="Ponieważ wybrałeś: - język polski, - zainteresowanie historią i zawodami prawniczymi, - brak zainteresowania zwiedzaniem zabytków."
metafora_psychologia="Ponieważ wybrałeś: - język polski - brak zainteresowania historią, nauką języków, pisaniem artykułów i wychowaniem."
metafora_rachunkowosc="Ponieważ wybrałeś: - matematykę, - brak zainteresowań naukami przyrodniczymi, - zainteresowanie pracą księgowego oraz nowinkami finansowymi."
metafora_rolnictwo="Ponieważ wybrałeś: - matematyka, - nauki przyrodnicze,  - brak zainteresowań pracą w laboratorium, rysunkiem technicznym, leczeniem i wiedzą geograficzną."
metafora_stosunkimiedzynarodowe="Ponieważ wybrałeś: - język polski, - brak zainteresowania historią, - zainteresowanie nauką języków obcych."



